CREATE TABLE IF NOT EXISTS `Djuchuu` (
  `JuchuuNO` varchar(12) NOT NULL,
  `DataKBN` smallint(6) DEFAULT NULL,
  `UserKBN` smallint(6) DEFAULT NULL,
  `SystemKBN` smallint(6) DEFAULT NULL,
  `KijunDate` date DEFAULT NULL,
  `ZigyoushoCD` varchar(6) DEFAULT NULL,
  `BumonCD` varchar(6) DEFAULT NULL,
  `TantoushaCD` varchar(10) DEFAULT NULL,
  `HacchuuDate` date DEFAULT NULL,
  `KaikeiYYMM` int(11) DEFAULT NULL,
  `NouhinDate` date DEFAULT NULL,
  `KenshuuYoteiDate` date DEFAULT NULL,
  `SiireYoteiDate` date DEFAULT NULL,
  `SiiresakiCD` varchar(10) DEFAULT NULL,
  `SiiresakiName` varchar(40) DEFAULT NULL,
  `SiharaisakiCD` varchar(10) DEFAULT NULL,
  `SiharaisakiName` varchar(40) DEFAULT NULL,
  `ShouhizeiNaigaiHyoukiKBN` tinyint(4) DEFAULT NULL,
  `TuukaCD` varchar(3) DEFAULT NULL,
  `RateKBN` smallint(6) DEFAULT NULL,
  `SiireRate` decimal(12,6) NOT NULL DEFAULT '0.000000',
  `SoukoCD` varchar(10) DEFAULT NULL,
  `HaisouGyoushaCD` varchar(10) DEFAULT NULL,
  `SiiresakiChuumonNO` varchar(20) DEFAULT NULL,
  `AnkenNO` varchar(30) DEFAULT NULL,
  `HacchuuDenpyouTekiyou` varchar(40) DEFAULT NULL,
  `DenpyouSiireHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouSiireHenpinHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouSiireNebikiHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouSiireShouhizeiGaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouJoudaiHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouJoudaiShouhizeiGaku` decimal(15,0) NOT NULL DEFAULT '0',
  `DenpyouGaikaSiireHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `DenpyouGaikaSiireHenpinHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `DenpyouGaikaSiireNebikiHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `DenpyouGaikaSiireShouhizeiGaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `DenpyouGaikaJoudaiHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `DenpyouGaikaJoudaiShouhizeiGaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SiharaiKBN` tinyint(4) DEFAULT NULL,
  `SiharaiChouhaKBN` tinyint(4) DEFAULT NULL,
  `SiharaiHouhouCD` varchar(5) DEFAULT NULL,
  `SiharaiYoteiDate` date DEFAULT NULL,
  `HacchuushoTekiyou` varchar(200) DEFAULT NULL,
  `HacchuushoHuyouFLG` tinyint(1) NOT NULL DEFAULT '0',
  `HacchuushoHakkouTaishouFLG` tinyint(1) NOT NULL DEFAULT '1',
  `HacchuushoHakkouFLG` tinyint(1) NOT NULL DEFAULT '0',
  `HacchuushoHakkouDatetime` datetime DEFAULT NULL,
  `HacchuuNO` varchar(12) DEFAULT NULL,
  `HacchuuGyouNO` smallint(6) DEFAULT NULL,
  `NyuukaYoteiKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `NyuukaKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `SiireKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `SubSystemDenpyouNO` varchar(12) DEFAULT NULL,
  `MitumoriNO` varchar(12) DEFAULT NULL,
  `MitumoriNOEdaban` smallint(6) DEFAULT NULL,
  `AnkenGuid` binary(16) DEFAULT NULL,
  `ShouninJoutaiKBN` smallint(6) DEFAULT NULL,
  `KihyouUserID` varchar(128) DEFAULT NULL,
  `CurrentUserID` varchar(128) DEFAULT NULL,
  `ShouninUserID` varchar(128) DEFAULT NULL,
  `ShouninDatetime` datetime DEFAULT NULL,
  `MaeAnkenGuid` binary(16) DEFAULT NULL,
  `ZigyoushoGroup1CD` varchar(3) DEFAULT NULL,
  `ZigyoushoGroup2CD` varchar(3) DEFAULT NULL,
  `BumonGroup1CD` varchar(3) DEFAULT NULL,
  `BumonGroup2CD` varchar(3) DEFAULT NULL,
  `BumonGroup3CD` varchar(3) DEFAULT NULL,
  `SiiresakiSeisikiName` varchar(120) DEFAULT NULL,
  `SiiresakiYuubinNO1` varchar(3) DEFAULT NULL,
  `SiiresakiYuubinNO2` varchar(4) DEFAULT NULL,
  `SiiresakiJuusho1` varchar(50) DEFAULT NULL,
  `SiiresakiJuusho2` varchar(50) DEFAULT NULL,
  `SiiresakiJuusho3` varchar(50) DEFAULT NULL,
  `SiiresakiJuusho4` varchar(50) DEFAULT NULL,
  `SiiresakiJuusho5` varchar(50) DEFAULT NULL,
  `SiiresakiTelNO1` varchar(6) DEFAULT NULL,
  `SiiresakiTelNO2` varchar(5) DEFAULT NULL,
  `SiiresakiTelNO3` varchar(5) DEFAULT NULL,
  `SiiresakiFaxNO1` varchar(6) DEFAULT NULL,
  `SiiresakiFaxNO2` varchar(5) DEFAULT NULL,
  `SiiresakiFaxNO3` varchar(5) DEFAULT NULL,
  `SiiresakiTel` varchar(20) DEFAULT NULL,
  `SiiresakiFax` varchar(20) DEFAULT NULL,
  `SiiresakiTantouBushoName` varchar(40) DEFAULT NULL,
  `SiiresakiTantoushaYakushoku` varchar(20) DEFAULT NULL,
  `SiiresakiTantoushaName` varchar(30) DEFAULT NULL,
  `SiharaisakiSeisikiName` varchar(120) DEFAULT NULL,
  `SiharaisakiYuubinNO1` varchar(3) DEFAULT NULL,
  `SiharaisakiYuubinNO2` varchar(4) DEFAULT NULL,
  `SiharaisakiJuusho1` varchar(50) DEFAULT NULL,
  `SiharaisakiJuusho2` varchar(50) DEFAULT NULL,
  `SiharaisakiJuusho3` varchar(50) DEFAULT NULL,
  `SiharaisakiJuusho4` varchar(50) DEFAULT NULL,
  `SiharaisakiJuusho5` varchar(50) DEFAULT NULL,
  `SiharaisakiTelNO1` varchar(6) DEFAULT NULL,
  `SiharaisakiTelNO2` varchar(5) DEFAULT NULL,
  `SiharaisakiTelNO3` varchar(5) DEFAULT NULL,
  `SiharaisakiFaxNO1` varchar(6) DEFAULT NULL,
  `SiharaisakiFaxNO2` varchar(5) DEFAULT NULL,
  `SiharaisakiFaxNO3` varchar(5) DEFAULT NULL,
  `SiharaisakiTel` varchar(20) DEFAULT NULL,
  `SiharaisakiFax` varchar(20) DEFAULT NULL,
  `SiharaisakiTantouBushoName` varchar(40) DEFAULT NULL,
  `SiharaisakiTantoushaYakushoku` varchar(20) DEFAULT NULL,
  `SiharaisakiTantoushaName` varchar(30) DEFAULT NULL,
  `UpdateDatetime` datetime NOT NULL,
  `UpdateJobID` varchar(128) NOT NULL,
  `UpdateUserID` varchar(128) NOT NULL,
  `UpdateComputerName` varchar(128) NOT NULL,
  `UpdateComputerUserName` varchar(128) NOT NULL,
  `UpdateComputerDomainName` varchar(256) NOT NULL,
  `SoufusakiName` varchar(50) NOT NULL,
  `SoufusakiKana` varchar(50) NOT NULL,
  `SoufusakiYuubinNO` varchar(8) NOT NULL,
  `SoufusakiJuusho1` varchar(50) NOT NULL,
  `SoufusakiJuusho2` varchar(50) NOT NULL,
  `SoufusakiBushoName` varchar(50) NOT NULL,
  `SoufusakiTantoushaName` varchar(50) NOT NULL,
  `SoufusakiTel` varchar(13) NOT NULL,
  `SoufusakiFax` varchar(13) NOT NULL,
  `RiyoukigyouCD` varchar(13) NOT NULL,
  `OguchiFLG` int(11) NOT NULL,
  `ShoninFLG` int(11) NOT NULL,
  `HacchuDatetime` datetime DEFAULT NULL,
  `TokuisakiCD` varchar(10) DEFAULT NULL,
  `JuchuuDatetime` datetime DEFAULT NULL,
  `ShukkaDate` date DEFAULT NULL,
  `ShukkaAnnaishoDatetime` datetime DEFAULT NULL,
  `NouhinbinName` varchar(50) DEFAULT NULL,
  `TrackingNo` varchar(50) DEFAULT NULL,
  `NounyusakiName` varchar(50) NOT NULL,
  `BinName` varchar(30) DEFAULT NULL,
  `BinNameBikou` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`JuchuuNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;