CREATE TABLE IF NOT EXISTS `Djuchuumeisai` (
  `JuchuuNO` varchar(12) NOT NULL,
  `JuchuuGyouNO` smallint(6) NOT NULL DEFAULT '0',
  `DataKBN` smallint(6) DEFAULT NULL,
  `UserKBN` smallint(6) DEFAULT NULL,
  `SystemKBN` smallint(6) DEFAULT NULL,
  `SaimuKamokuKBN` tinyint(4) DEFAULT NULL,
  `GyouHyouziJun` smallint(6) NOT NULL DEFAULT '0',
  `HinshuCategoryCD` varchar(10) DEFAULT NULL,
  `HinshuCD` varchar(10) DEFAULT NULL,
  `ShouhinCD` varchar(25) DEFAULT NULL,
  `ShouhinName` varchar(100) DEFAULT NULL,
  `Kikaku` varchar(60) DEFAULT NULL,
  `LotKanriFLG` tinyint(1) NOT NULL DEFAULT '0',
  `Kakeritu` decimal(7,2) NOT NULL DEFAULT '0.00',
  `AitesakiHinNO` varchar(30) DEFAULT NULL,
  `AitesakiHinName` varchar(100) DEFAULT NULL,
  `NisugataTaniCD` varchar(2) DEFAULT NULL,
  `IriSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `NiSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `NisugataTaniCD2` varchar(2) DEFAULT NULL,
  `IriSuu2` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `NiSuu2` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `BaraSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `HacchuuSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `TaniCD` varchar(2) DEFAULT NULL,
  `KariTankaKBN` tinyint(4) NOT NULL DEFAULT '0',
  `SiireTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SiireTankaShouhizei` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SiireHontaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SiireKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `SiireHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `SiireShouhizeiGaku` decimal(15,0) NOT NULL DEFAULT '0',
  `SiireShouhizeiChouseiGaku` decimal(15,0) NOT NULL DEFAULT '0',
  `JoudaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `JoudaiTankaShouhizei` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `JoudaiHontaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `JoudaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `JoudaiHontaiKingaku` decimal(15,0) NOT NULL DEFAULT '0',
  `JoudaiShouhizeiGaku` decimal(15,0) NOT NULL DEFAULT '0',
  `GaikaSiireTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireTankaShouhizei` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireHontaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireShouhizeiGaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaSiireShouhizeiChouseiGaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiTankaShouhizei` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiHontaiTanka` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiHontaiKingaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `GaikaJoudaiShouhizeiGaku` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `ShouhizeirituKBN` tinyint(4) DEFAULT NULL,
  `ShouhizeiNaigaiKBN` tinyint(4) DEFAULT NULL,
  `HacchuuMeisaiTekiyou` varchar(40) DEFAULT NULL,
  `ShouninJoutaiKBN` varchar(20) DEFAULT NULL,
  `NouhinDate` date DEFAULT NULL,
  `SiireYoteiDate` date DEFAULT NULL,
  `KenshuuYoteiDate` date DEFAULT NULL,
  `ZaikoKBN` smallint(6) DEFAULT NULL,
  `SoukoCD` varchar(10) DEFAULT NULL,
  `ZaikoBashoCD` varchar(10) DEFAULT NULL,
  `NyuukaYoteiHoryuuFLG` tinyint(1) NOT NULL DEFAULT '0',
  `NyuukaHoryuuFLG` tinyint(1) NOT NULL DEFAULT '0',
  `NyuukaYoteiKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `NyuukaKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `SiireKanryouKBN` tinyint(4) NOT NULL DEFAULT '0',
  `NyuukaYoteiSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `NyuukaSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SiireSuu` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `SegmentCD1` varchar(10) DEFAULT NULL,
  `SegmentCD2` varchar(10) DEFAULT NULL,
  `SegmentCD3` varchar(10) DEFAULT NULL,
  `HacchuuNO` varchar(12) DEFAULT NULL,
  `HacchuuGyouNO` smallint(6) DEFAULT NULL,
  `TorikesiFLG` tinyint(1) NOT NULL DEFAULT '0',
  `SubSystemDenpyouNO` varchar(12) DEFAULT NULL,
  `SubSystemDenpyouGyouNO` smallint(6) DEFAULT NULL,
  `MitumoriNO` varchar(12) DEFAULT NULL,
  `MitumoriNOEdaban` smallint(6) DEFAULT NULL,
  `MitumoriGenkaGyouNO` smallint(6) DEFAULT NULL,
  `SiharaiIraiNO` varchar(12) DEFAULT NULL,
  `HacchuuIraiNO` varchar(12) DEFAULT NULL,
  `HacchuuIraiGyouNO` smallint(6) NOT NULL,
  `UpdateDatetime` datetime NOT NULL,
  `UpdateJobID` varchar(128) NOT NULL,
  `UpdateUserID` varchar(128) NOT NULL,
  `UpdateComputerName` varchar(128) NOT NULL,
  `UpdateComputerUserName` varchar(128) NOT NULL,
  `UpdateComputerDomainName` varchar(256) NOT NULL,
  `RiyoukigyouCD` varchar(10) NOT NULL,
  `SiiresakiCD` varchar(10) NOT NULL,
  `JoutaiFLG` int(11) NOT NULL,
  `SoufusakiNouhinKibouDate` date DEFAULT NULL,
  `KihyouUserID` varchar(128) NOT NULL COMMENT '起票ユーザID',
  `CurrentUserID` varchar(128) NOT NULL COMMENT '現在ユーザID',
  `ShouninUserID` varchar(128) DEFAULT NULL COMMENT '承認ユーザID',
  `ShouninDatetime` datetime DEFAULT NULL COMMENT '承認日時',
  PRIMARY KEY (`JuchuuNO`,`JuchuuGyouNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;