CREATE TABLE IF NOT EXISTS `Mbumon` (
  `ZigyoushoCD` varchar(6) NOT NULL,
  `BumonCD` varchar(6) NOT NULL,
  `KaiteiDate` date NOT NULL,
  `BumonSeisikiName` varchar(30) DEFAULT NULL,
  `BumonName` varchar(20) DEFAULT NULL,
  `BumonKanaName` varchar(30) DEFAULT NULL,
  `Hyouzijun` smallint(6) NOT NULL DEFAULT '0',
  `OyaBumonCD` varchar(6) DEFAULT NULL,
  `BumonGroup1CD` varchar(3) DEFAULT NULL,
  `BumonGroup2CD` varchar(3) DEFAULT NULL,
  `BumonGroup3CD` varchar(3) DEFAULT NULL,
  `YuubinNO1` varchar(3) DEFAULT NULL,
  `YuubinNO2` varchar(4) DEFAULT NULL,
  `Juusho1` varchar(50) DEFAULT NULL,
  `Juusho1KanaName` varchar(50) DEFAULT NULL,
  `Juusho2` varchar(50) DEFAULT NULL,
  `Juusho2KanaName` varchar(50) DEFAULT NULL,
  `TelNO1` varchar(6) DEFAULT NULL,
  `TelNO2` varchar(5) DEFAULT NULL,
  `TelNO3` varchar(5) DEFAULT NULL,
  `FaxNO1` varchar(6) DEFAULT NULL,
  `FaxNO2` varchar(5) DEFAULT NULL,
  `FaxNO3` varchar(5) DEFAULT NULL,
  `EiziChouhyouInziBumonName` varchar(100) DEFAULT NULL,
  `EiziJuusho1` varchar(50) DEFAULT NULL,
  `EiziJuusho2` varchar(50) DEFAULT NULL,
  `EiziJuusho3` varchar(50) DEFAULT NULL,
  `EiziTel` varchar(20) DEFAULT NULL,
  `EiziFax` varchar(20) DEFAULT NULL,
  `SiyouShuuryouDate` date DEFAULT NULL,
  `KaikeiBumonCD` varchar(6) DEFAULT NULL,
  `CannotDeleteFLG` tinyint(1) NOT NULL DEFAULT '0',
  `KasidasisoukoCD` varchar(10) DEFAULT NULL,
  `HikitorisoukoCD` varchar(10) DEFAULT NULL,
  `HunsitusoukoCD` varchar(10) DEFAULT NULL,
  `HanbaihinsoukoCD` varchar(10) DEFAULT NULL,
  `SeikyuushoinziKessaiKouzaCD1` varchar(3) DEFAULT NULL,
  `SeikyuushoinziKessaiKouzaCD2` varchar(3) DEFAULT NULL,
  `SeikyuushoinziKessaiKouzaCD3` varchar(3) DEFAULT NULL,
  `OskYobi01` varchar(40) DEFAULT NULL,
  `OskYobi02` varchar(40) DEFAULT NULL,
  `OskYobi03` varchar(40) DEFAULT NULL,
  `OskYobi04` varchar(40) DEFAULT NULL,
  `OskYobi05` varchar(40) DEFAULT NULL,
  `OskYobi06` varchar(40) DEFAULT NULL,
  `OskYobi07` varchar(40) DEFAULT NULL,
  `OskYobi08` varchar(40) DEFAULT NULL,
  `OskYobi09` varchar(40) DEFAULT NULL,
  `OskYobi10` varchar(40) DEFAULT NULL,
  `OskYobi11` varchar(40) DEFAULT NULL,
  `OskYobi12` varchar(40) DEFAULT NULL,
  `OskYobi13` varchar(40) DEFAULT NULL,
  `OskYobi14` varchar(40) DEFAULT NULL,
  `OskYobi15` varchar(40) DEFAULT NULL,
  `OskYobi31` int(11) NOT NULL DEFAULT '0',
  `OskYobi32` int(11) NOT NULL DEFAULT '0',
  `OskYobi33` int(11) NOT NULL DEFAULT '0',
  `OskYobi34` int(11) NOT NULL DEFAULT '0',
  `OskYobi35` int(11) NOT NULL DEFAULT '0',
  `OskYobi36` int(11) NOT NULL DEFAULT '0',
  `OskYobi37` int(11) NOT NULL DEFAULT '0',
  `OskYobi38` int(11) NOT NULL DEFAULT '0',
  `OskYobi39` int(11) NOT NULL DEFAULT '0',
  `OskYobi40` int(11) NOT NULL DEFAULT '0',
  `OskYobi51` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi52` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi53` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi54` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi55` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi56` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi57` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi58` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi59` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi60` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi71` date DEFAULT NULL,
  `OskYobi72` date DEFAULT NULL,
  `OskYobi73` date DEFAULT NULL,
  `OskYobi74` date DEFAULT NULL,
  `OskYobi75` date DEFAULT NULL,
  `UpdateDatetime` datetime DEFAULT NULL,
  `UpdateJobID` varchar(128) NOT NULL,
  `UpdateUserID` varchar(128) NOT NULL,
  `UpdateComputerName` varchar(128) NOT NULL,
  `UpdateComputerUserName` varchar(128) NOT NULL,
  `UpdateComputerDomainName` varchar(256) NOT NULL,
  PRIMARY KEY (`BumonCD`,`KaiteiDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;