CREATE TABLE IF NOT EXISTS `Msiiresaki` (
  `SiiresakiCD` varchar(10) NOT NULL,
  `SiiresakiSeisikiName` varchar(120) DEFAULT NULL,
  `SiiresakiName` varchar(40) DEFAULT NULL,
  `SiiresakiKanaName` varchar(40) DEFAULT NULL,
  `YuubinNO1` varchar(3) DEFAULT NULL,
  `YuubinNO2` varchar(4) DEFAULT NULL,
  `Juusho1` varchar(50) DEFAULT NULL,
  `Juusho2` varchar(50) DEFAULT NULL,
  `Juusho3` varchar(50) DEFAULT NULL,
  `Juusho4` varchar(50) DEFAULT NULL,
  `Juusho5` varchar(50) DEFAULT NULL,
  `TelNO1_1` varchar(6) DEFAULT NULL,
  `TelNO1_2` varchar(5) DEFAULT NULL,
  `TelNO1_3` varchar(5) DEFAULT NULL,
  `NaisenNO1` varchar(10) DEFAULT NULL,
  `TelNO2_1` varchar(6) DEFAULT NULL,
  `TelNO2_2` varchar(5) DEFAULT NULL,
  `TelNO2_3` varchar(5) DEFAULT NULL,
  `NaisenNO2` varchar(10) DEFAULT NULL,
  `FaxNO1_1` varchar(6) DEFAULT NULL,
  `FaxNO1_2` varchar(5) DEFAULT NULL,
  `FaxNO1_3` varchar(5) DEFAULT NULL,
  `Tel` varchar(20) DEFAULT NULL,
  `Fax` varchar(20) DEFAULT NULL,
  `TantouBushoName` varchar(40) DEFAULT NULL,
  `TantouYakushokuName` varchar(20) DEFAULT NULL,
  `TantoushaName` varchar(30) DEFAULT NULL,
  `MailAddress` varchar(128) DEFAULT NULL,
  `SiharaisakiCD` varchar(10) DEFAULT NULL,
  `TantoushaCD` varchar(10) DEFAULT NULL,
  `TantoushaIdouDate` date DEFAULT NULL,
  `SinTantoushaCD` varchar(10) DEFAULT NULL,
  `ZaikoKanriZigyoushoCD` varchar(6) DEFAULT NULL,
  `ShokutiFLG` tinyint(1) NOT NULL DEFAULT '0',
  `SegmentCD1` varchar(10) DEFAULT NULL,
  `SegmentCD2` varchar(10) DEFAULT NULL,
  `SegmentCD3` varchar(10) DEFAULT NULL,
  `HacchuushoHuyouFLG` tinyint(1) NOT NULL DEFAULT '0',
  `HacchuushoSokudenKBN` smallint(6) DEFAULT '0',
  `DMHuyouFLG` tinyint(1) NOT NULL DEFAULT '0',
  `NyuukaKeijouMoto` tinyint(4) DEFAULT NULL,
  `SiireKeijouKijun` tinyint(4) DEFAULT NULL,
  `SaimuKamokuKBN` tinyint(4) DEFAULT NULL,
  `TorihikiKaisiDate` date DEFAULT NULL,
  `TorihikiShuuryouDate` date DEFAULT NULL,
  `KaikeiTorihikisakiCD` varchar(10) DEFAULT NULL,
  `DenpyouSaidaiGyousuu` smallint(6) DEFAULT NULL,
  `YuukouKigenCheckKBN` tinyint(4) DEFAULT NULL,
  `KihonTuukaCD` varchar(3) DEFAULT NULL,
  `CannotDeleteFLG` tinyint(1) NOT NULL DEFAULT '0',
  `OskYobi01` varchar(10) DEFAULT NULL,
  `OskYobi02` varchar(10) DEFAULT NULL,
  `OskYobi03` varchar(10) DEFAULT NULL,
  `OskYobi04` varchar(10) DEFAULT NULL,
  `OskYobi05` varchar(10) DEFAULT NULL,
  `OskYobi06` varchar(10) DEFAULT NULL,
  `OskYobi07` varchar(10) DEFAULT NULL,
  `OskYobi08` varchar(5) DEFAULT NULL,
  `OskYobi09` varchar(5) DEFAULT NULL,
  `OskYobi10` varchar(5) DEFAULT NULL,
  `OskYobi11` varchar(5) DEFAULT NULL,
  `OskYobi12` varchar(5) DEFAULT NULL,
  `OskYobi13` varchar(5) DEFAULT NULL,
  `OskYobi14` varchar(5) DEFAULT NULL,
  `OskYobi15` varchar(5) DEFAULT NULL,
  `OskYobi16` varchar(5) DEFAULT NULL,
  `OskYobi17` varchar(5) DEFAULT NULL,
  `OskYobi18` varchar(5) DEFAULT NULL,
  `OskYobi19` varchar(5) DEFAULT NULL,
  `OskYobi20` varchar(5) DEFAULT NULL,
  `OskYobi21` varchar(5) DEFAULT NULL,
  `OskYobi22` varchar(5) DEFAULT NULL,
  `OskYobi23` varchar(5) DEFAULT NULL,
  `OskYobi24` varchar(5) DEFAULT NULL,
  `OskYobi25` varchar(5) DEFAULT NULL,
  `OskYobi26` varchar(5) DEFAULT NULL,
  `OskYobi27` varchar(5) DEFAULT NULL,
  `OskYobi28` varchar(5) DEFAULT NULL,
  `OskYobi29` varchar(5) DEFAULT NULL,
  `OskYobi30` varchar(5) DEFAULT NULL,
  `OskYobi31` int(11) NOT NULL DEFAULT '0',
  `OskYobi32` int(11) NOT NULL DEFAULT '0',
  `OskYobi33` int(11) NOT NULL DEFAULT '0',
  `OskYobi34` int(11) NOT NULL DEFAULT '0',
  `OskYobi35` int(11) NOT NULL DEFAULT '0',
  `OskYobi36` int(11) NOT NULL DEFAULT '0',
  `OskYobi37` int(11) NOT NULL DEFAULT '0',
  `OskYobi38` int(11) NOT NULL DEFAULT '0',
  `OskYobi39` int(11) NOT NULL DEFAULT '0',
  `OskYobi40` int(11) NOT NULL DEFAULT '0',
  `OskYobi41` int(11) NOT NULL DEFAULT '0',
  `OskYobi42` int(11) NOT NULL DEFAULT '0',
  `OskYobi43` int(11) NOT NULL DEFAULT '0',
  `OskYobi44` int(11) NOT NULL DEFAULT '0',
  `OskYobi45` int(11) NOT NULL DEFAULT '0',
  `OskYobi46` int(11) NOT NULL DEFAULT '0',
  `OskYobi47` int(11) NOT NULL DEFAULT '0',
  `OskYobi48` int(11) NOT NULL DEFAULT '0',
  `OskYobi49` int(11) NOT NULL DEFAULT '0',
  `OskYobi50` int(11) NOT NULL DEFAULT '0',
  `OskYobi51` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi52` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi53` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi54` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi55` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi56` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi57` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi58` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi59` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi60` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi61` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi62` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi63` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi64` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi65` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi66` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi67` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi68` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi69` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi70` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi71` date DEFAULT NULL,
  `OskYobi72` date DEFAULT NULL,
  `OskYobi73` date DEFAULT NULL,
  `OskYobi74` date DEFAULT NULL,
  `OskYobi75` date DEFAULT NULL,
  `UpdateDatetime` datetime NOT NULL,
  `UpdateJobID` varchar(128) NOT NULL,
  `UpdateUserID` varchar(128) NOT NULL,
  `UpdateComputerName` varchar(128) NOT NULL,
  `UpdateComputerUserName` varchar(128) NOT NULL,
  `UpdateComputerDomainName` varchar(256) NOT NULL,
  `Settoji` varchar(3) NOT NULL,
  PRIMARY KEY (`SiiresakiCD`),
  KEY `SiharaisakiCD` (`SiharaisakiCD`),
  KEY `TantoushaCD` (`TantoushaCD`),
  KEY `ZaikoKanriZigyoushoCD` (`ZaikoKanriZigyoushoCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;