CREATE TABLE IF NOT EXISTS `Mtani` (
  `TaniCD` varchar(2) NOT NULL,
  `TaniName` varchar(10) DEFAULT NULL,
  `TaniKigou` varchar(6) DEFAULT NULL,
  `EiziTaniKigou` varchar(6) DEFAULT NULL,
  `CannotDeleteFLG` tinyint(1) NOT NULL DEFAULT '0',
  `OskYobi01` varchar(5) DEFAULT NULL,
  `OskYobi02` varchar(5) DEFAULT NULL,
  `OskYobi03` varchar(5) DEFAULT NULL,
  `OskYobi04` varchar(5) DEFAULT NULL,
  `OskYobi05` varchar(5) DEFAULT NULL,
  `OskYobi06` varchar(5) DEFAULT NULL,
  `OskYobi07` varchar(5) DEFAULT NULL,
  `OskYobi08` varchar(5) DEFAULT NULL,
  `OskYobi09` varchar(5) DEFAULT NULL,
  `OskYobi10` varchar(5) DEFAULT NULL,
  `OskYobi31` int(11) NOT NULL DEFAULT '0',
  `OskYobi32` int(11) NOT NULL DEFAULT '0',
  `OskYobi33` int(11) NOT NULL DEFAULT '0',
  `OskYobi34` int(11) NOT NULL DEFAULT '0',
  `OskYobi35` int(11) NOT NULL DEFAULT '0',
  `OskYobi51` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi52` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi53` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi54` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi55` decimal(21,6) NOT NULL DEFAULT '0.000000',
  `OskYobi71` date DEFAULT NULL,
  `OskYobi72` date DEFAULT NULL,
  `OskYobi73` date DEFAULT NULL,
  `OskYobi74` date DEFAULT NULL,
  `OskYobi75` date DEFAULT NULL,
  `UpdateDatetime` datetime NOT NULL,
  `UpdateJobID` varchar(128) NOT NULL,
  `UpdateUserID` varchar(128) NOT NULL,
  `UpdateComputerName` varchar(128) NOT NULL,
  `UpdateComputerUserName` varchar(128) NOT NULL,
  `UpdateComputerDomainName` varchar(256) NOT NULL,
  PRIMARY KEY (`TaniCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
